apiVersion: apps/v1
kind: Deployment
metadata:
  name: vg-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 381492200529.dkr.ecr.us-east-1.amazonaws.com/project1-ecr:8
      imagePullSecrets:
        - name: ecr-registry
