apiVersion: apps/v1
kind: Deployment
metadata:
  name: vg-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 294176318510.dkr.ecr.us-east-1.amazonaws.com/super30_ecr/:1
      imagePullSecrets:
        - name: ecr-registry
