apiVersion: apps/v1
kind: Deployment
metadata:
  name: vg-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 294176318510.dkr.ecr.us-east-1.amazonaws.com/super30_ecr:latest  # Replace 'latest' with the desired tag
        ports:
        - containerPort: 8080
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_IMAGE_NAME
          value: "294176318510.dkr.ecr.us-east-1.amazonaws.com/super30_ecr:latest"  # Adjust this to the current tag
      imagePullSecrets:
      - name: ecr-registry
